version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "8001:3000"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
