version: '3.8'
services:
  frontend:
    build:
      context: .
    command: npm run dev
    ports:
      - "8001:3000"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
    environment:
      - NEXT_API_URL=$NEXT_API_URL
      - NEXT_INTERNAL_API_URL=$NEXT_INTERNAL_API_URL
      - NEXT_INTERNAL_API_AUTH_URL=$NEXT_INTERNAL_API_AUTH_URL
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET

