version: '3.8'
services:
  frontend:
    build:
      context: .
    restart: always
    command: sh -c "npm run build && npm run start"
    environment:
      - NEXT_API_URL=$NEXT_API_URL
      - NEXT_INTERNAL_API_URL=$NEXT_INTERNAL_API_URL
      - NEXT_INTERNAL_API_AUTH_URL=$NEXT_INTERNAL_API_AUTH_URL
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
      - WATCHPACK_POLLING=true
