# get the base node image
FROM node:18-alpine as builder

# set the working dir for container
WORKDIR /frontend

# copy the json file first
COPY --chown=node:node ./package.json .
COPY --chown=node:node ./package-lock.json .

# install npm dependencies
RUN npm install

# copy other project files
COPY --chown=node:node . .
USER node
