version: '3.8'
services:
  frontend:
    build:
      context: .
    command: npm run dev
    ports:
      - "8001:3000"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
    environment:
      - NEXT_API_URL="http://localhost"
      - NEXT_INTERNAL_API_URL="http://localhost/api/"
