site_name: Dr Trottoir Backend Documentation
# TODO repo_url: https://github.com/SELab-2/Dr-Trottoir-3

theme:
  name: "readthedocs"

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Backend: 'backend\testcalc.md'