version: '3.8'
services:
  caddy:
    image: caddy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
    networks:
      - selab

  backend:
    extends:
      file: ../backend/docker-compose.dev.yml
      service: backend
    build: 
      network: host
      context: ../backend
    networks:
      - selab

  db:
    extends:
      file: ../backend/docker-compose.dev.yml
      service: db
    networks:
      selab:
        aliases:
          - db

  docs:
    extends:
      file: ../backend/docs/docker-compose.yml
      service: docs
    build: 
      network: host
      context: ../backend
    networks:
      - selab

  frontend:
    extends:
      file: ../frontend/docker-compose.dev.yml
      service: frontend
    build: 
      network: host
      context: ../frontend
    networks:
      - selab

networks:
  selab:
volumes:
  postgres-data:
