version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: sh -c "make venv && make lint && make test"
    volumes:
      - ./:/app/
      - /app/venv/
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=hello_django
      - DB_PASS=hello_django
      - DATABASE=postgres
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
