# pull official base image
FROM python:3.10-alpine

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set work directory
WORKDIR /app

# install psycopg2 dependencies
RUN apk update && \
    apk add postgresql-dev gcc python3-dev musl-dev libffi-dev zlib-dev jpeg-dev linux-headers make && \
    mkdir -p /vol/web/static && \
    mkdir -p /vol/web/media
