version: '3.8'

services:
  backend:
    build:
      network: host
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=$SECRET_KEY
      - BASE_PATH=$BASE_PATH
      - DEBUG=$DEBUG
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - ALLOWED_HOSTS=$ALLOWED_HOSTS
      - CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  postgres-data:
