version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: sh -c "rsync -r /app_host/ /app/ && make venv && make lint && /app/venv/bin/python manage.py wait_for_db && make test"
    volumes:
      - ./:/app_host/:ro
      - /app/
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=hello_django
      - DB_PASS=hello_django
      - DATABASE=postgres
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
