version: '3.8'

services:
  backend:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=hello_django
      - DB_PASS=hello_django
      - DATABASE=postgres
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
    ports:
      - "5432:5432"
