[tool.isort]
profile = "black"
skip = "migrations"

[tool.black]
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
    migrations
)
'''

[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

# This module does not provide a stubs file or any typing hints
[[tool.mypy.overrides]]
module = "rest_framework_simplejwt.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "drf_yasg.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "sendgrid.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "django_filters.*"
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "drtrottoir.settings"
