# Generated by Django 4.1.7 on 2023-02-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('building_guide_pdf_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GarbageCollectionScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.building')),
            ],
        ),
        migrations.CreateModel(
            name='GarbageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
                ('buildings', models.ManyToManyField(to='drtrottoir.building')),
                ('location_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drtrottoir.locationgroup')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drtrottoir.locationgroup')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drtrottoir.role')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleWorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField()),
                ('image_path', models.CharField(max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.building')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.user')),
                ('schedule_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.scheduledefinition')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('schedule_definition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drtrottoir.scheduledefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drtrottoir.user')),
            ],
        ),
        migrations.CreateModel(
            name='IssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.issue')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='approval_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issues_to_approve', to='drtrottoir.user'),
        ),
        migrations.AddField(
            model_name='issue',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issues_created', to='drtrottoir.user'),
        ),
        migrations.CreateModel(
            name='GarbageCollectionScheduleTemplateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('garbage_collection_schedule_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.garbagecollectionscheduletemplate')),
                ('garbage_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drtrottoir.garbagetype')),
            ],
        ),
        migrations.CreateModel(
            name='GarbageCollectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_day', models.DateField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drtrottoir.building')),
                ('garbage_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drtrottoir.garbagetype')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='location_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drtrottoir.locationgroup'),
        ),
    ]
