# Generated by Django 4.1.7 on 2023-02-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='building_guide_pdf_path',
            new_name='guide_pdf_path',
        ),
        migrations.RenameField(
            model_name='locationgroup',
            old_name='location_group_name',
            new_name='name',
        ),
    ]
