# Generated by Django 4.1.7 on 2023-03-04 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='location_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buildings', to='drtrottoir.locationgroup'),
        ),
        migrations.AlterField(
            model_name='garbagecollectionschedule',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='garbage_collection_schedules', to='drtrottoir.building'),
        ),
        migrations.AlterField(
            model_name='garbagecollectionschedule',
            name='garbage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='collection_schedules', to='drtrottoir.garbagetype'),
        ),
        migrations.AlterField(
            model_name='garbagecollectionscheduletemplate',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='garbage_collection_schedule_templates', to='drtrottoir.building'),
        ),
        migrations.AlterField(
            model_name='garbagecollectionscheduletemplateentry',
            name='garbage_collection_schedule_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='drtrottoir.garbagecollectionscheduletemplate'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issues', to='drtrottoir.building'),
        ),
        migrations.AlterField(
            model_name='issueimage',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='images', to='drtrottoir.issue'),
        ),
        migrations.AlterField(
            model_name='scheduleassignment',
            name='schedule_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='drtrottoir.scheduledefinition'),
        ),
        migrations.AlterField(
            model_name='scheduleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduledefinition',
            name='location_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedule_definitions', to='drtrottoir.locationgroup'),
        ),
        migrations.AlterField(
            model_name='scheduleworkentry',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedule_work_entries', to='drtrottoir.building'),
        ),
        migrations.AlterField(
            model_name='scheduleworkentry',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedule_work_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduleworkentry',
            name='schedule_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_entries', to='drtrottoir.scheduledefinition'),
        ),
        migrations.AlterField(
            model_name='student',
            name='location_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='drtrottoir.locationgroup'),
        ),
    ]
