# Generated by Django 4.1.7 on 2023-03-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drtrottoir", "0002_alter_building_location_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issueimage",
            name="image_path",
        ),
        migrations.AddField(
            model_name="issueimage",
            name="image",
            field=models.ImageField(default="", upload_to="issue_images"),
            preserve_default=False,
        ),
    ]
