# Generated by Django 4.1.7 on 2023-03-06 12:46

from django.db import migrations, models
import drtrottoir.models


class Migration(migrations.Migration):
    dependencies = [
        ("drtrottoir", "0003_remove_issueimage_image_path_issueimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduleworkentry",
            name="image_path",
        ),
        migrations.AddField(
            model_name="scheduleworkentry",
            name="image",
            field=models.ImageField(
                default="",
                upload_to=drtrottoir.models.get_file_path_schedule_work_entry_image,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="issueimage",
            name="image",
            field=models.ImageField(
                upload_to=drtrottoir.models.get_file_path_issue_image
            ),
        ),
    ]
