# Generated by Django 4.1.7 on 2023-03-06 13:16

from django.db import migrations, models
import drtrottoir.models


class Migration(migrations.Migration):
    dependencies = [
        ("drtrottoir", "0004_remove_scheduleworkentry_image_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="guide_pdf_path",
        ),
        migrations.AddField(
            model_name="building",
            name="image",
            field=models.FileField(
                default="", upload_to=drtrottoir.models.get_file_path_building_pdf_guide
            ),
            preserve_default=False,
        ),
    ]
