# Generated by Django 4.1.7 on 2023-03-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drtrottoir", "0008_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduleworkentry",
            name="schedule_definition",
        ),
        migrations.AddField(
            model_name="scheduleworkentry",
            name="schedule_assignment",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="work_entries",
                to="drtrottoir.scheduleassignment",
            ),
            preserve_default=False,
        ),
    ]
