# Generated by Django 4.1.7 on 2023-03-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drtrottoir", "0009_remove_scheduleworkentry_schedule_definition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleworkentry",
            name="entry_type",
            field=models.CharField(
                choices=[("AR", "Arrival"), ("WO", "Working"), ("DE", "Departure")],
                default="AR",
                max_length=2,
            ),
        ),
    ]
