# Generated by Django 4.1.7 on 2023-03-27 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drtrottoir", "0010_building_description_building_image_and_more"),
        ("drtrottoir", "0010_scheduleworkentry_entry_type"),
    ]

    operations = []
