# Generated by Django 4.1.7 on 2023-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drtrottoir", "0011_merge_20230327_1439"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="latitude",
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="longitude",
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
    ]
