# Generated by Django 4.1.7 on 2023-04-12 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drtrottoir", "0012_alter_syndicus_buildings"),
        ("drtrottoir", "0012_building_latitude_building_longitude"),
    ]

    operations = []
