# Generated by Django 4.1.7 on 2023-04-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drtrottoir", "0013_merge_20230412_0751"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
