# Generated by Django 4.1.7 on 2023-04-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drtrottoir", "0014_building_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="garbagecollectionscheduletemplate",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="garbagetype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="locationgroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name="garbagecollectionschedule",
            constraint=models.UniqueConstraint(
                fields=("for_day", "building", "garbage_type"),
                name="unique_for_day_building_garbage_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="garbagecollectionscheduletemplateentry",
            constraint=models.UniqueConstraint(
                fields=("day", "garbage_type", "garbage_collection_schedule_template"),
                name="unique_day_garbage_type_garbage_collection_schedule_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleassignment",
            constraint=models.UniqueConstraint(
                fields=("assigned_date", "schedule_definition"),
                name="unique_assigned_date_schedule_definition",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledefinition",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="unique_name_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledefinitionbuilding",
            constraint=models.UniqueConstraint(
                fields=("schedule_definition", "position"),
                name="unique_schedule_definition_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledefinitionbuilding",
            constraint=models.UniqueConstraint(
                fields=("schedule_definition", "building"),
                name="unique_schedule_definition_building",
            ),
        ),
    ]
