# Generated by Django 4.1.7 on 2023-04-29 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drtrottoir", "0012_building_secret_link"),
        ("drtrottoir", "0014_building_name"),
    ]

    operations = []
