# Generated by Django 4.1.7 on 2023-05-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0015_merge_0012_building_secret_link_0014_building_name'),
        ('drtrottoir', '0015_user_invite_link'),
    ]

    operations = [
    ]
