# Generated by Django 4.1.7 on 2023-05-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0016_merge_20230518_1538'),
        ('drtrottoir', '0016_user_reset_password_link'),
    ]

    operations = [
    ]
