# Generated by Django 4.1.7 on 2023-05-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drtrottoir', '0017_merge_20230520_1352'),
        ('drtrottoir', '0017_merge_20230520_1405'),
    ]

    operations = [
    ]
