import Head from 'next/head';
import styles from '@/styles/Home.module.css';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <main className={styles.main}>
                    <div style={{backgroundColor: 'white', width: '100%', height: '100%'}}>
                        <p>Not logged in, TODO: redirect to login page.</p>
                    </div>
                </main>
            </div>
        </>
    );
}
