import Head from 'next/head';
import NavBar from '../components/elements/navbarElement/Navbar';
import styles from '@/styles/Home.module.css';
import {useSession} from 'next-auth/react';

// eslint-disable-next-line require-jsdoc
export default function Home() {
    const {data: session} = useSession();

    console.log(session);

    if (session && session.user) {
        return (
            <>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main className={styles.main}>
                    <NavBar>
                        <div style={{backgroundColor: 'white', width: '100%', height: '100%'}}>
                            <p>Hi {session.user.name}, you are logged in (TODO: this is debug).</p>
                        </div>
                    </NavBar>
                </main>
            </>
        );
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body>
                <main className={styles.main}>
                    <NavBar>
                        <div style={{backgroundColor: 'white', width: '100%', height: '100%'}}>
                            <p>Not logged in, TODO: redirect to login page.</p>
                        </div>
                    </NavBar>
                </main>
            </body>
        </>
    );
}
