import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import {useSession} from 'next-auth/react';

// eslint-disable-next-line require-jsdoc
export default function Home() {
    const {data: session} = useSession();

    if (session && session.user) {
        return (
          <>
              <Head>
                  <title>Create Next App</title>
                  <meta name="description" content="Generated by create next app" />
                  <meta name="viewport" content="width=device-width, initial-scale=1" />
                  <link rel="icon" href="/favicon.ico" />
              </Head>
              <main className={styles.main}>
                  <div style={{backgroundColor: 'white', width: '100%', height: '100%'}}>
                      <p>Hi {session.user.name}, you are logged in (TODO: this is debug).</p>
                  </div>
              </main>
          </>
        );
    }

    return (
      <>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <div>
              <main className={styles.main}>
                  <div style={{backgroundColor: 'white', width: '100%', height: '100%'}}>
                      <p>Not logged in, TODO: redirect to login page.</p>
                  </div>
              </main>
          </div>
      </>
    );
}