name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: deploy
    steps:
      - uses: actions/checkout@v3
      - name: Make deploy.sh executable
        run: chmod +x deploy.sh
      - name: Run deploy.sh
        run: ./deploy.sh