name: Testing

on:
  pull_request:
    branches: ["main", "development"]

jobs:
  testing:
    runs-on: testing
    steps:
      - uses: actions/checkout@v3
      - name: Frontend
        run: sh test.sh frontend --build
      - name: Backend
        run: sh test.sh backend --build
