name: Testing

on:
  pull_request:
    branches: ["main", "development"]

jobs:
  backend:
    runs-on: testing
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Create venv
        run: make venv
      - name: Linting
        run: make lint
      - name: Testing
        run: make test


  frontend:
    runs-on: testing
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Building
        run: npm run build
