name: Linting & Testing

on:
  pull_request:
    branches: [main, development]
  push:
    branches: [jorispeeters/fix-ci-linting-and-testing]

jobs:
#  testing:
#    runs-on: testing
#    steps:
#      - uses: actions/checkout@v3
#      - name: Frontend
#        run: ./test.sh frontend --build
#      - name: Backend
#        run: ./test.sh backend --build
  backend-linting:
    runs-on: linting
    env:
      SRC: "drtrottoir"
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run Black
        run: black --check $SRC
      - name: Run Flake8
        run: flake8 $SRC
      - name: Run Isort
        run: isort --check $SRC
      - name: Run Mypy
        run: mypy $SRC

  frontend-linting:
    runs-on: linting
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
